
from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd

from .assumptions import (
    SCENARIOS,
    AssumptionRegister,
    DEFAULT_ASSUMPTIONS_PATH,
    DEFAULT_US_GEO_MULT_PATH,
    DEFAULT_CAN_GEO_MULT_PATH,
    GeoMultiplierTable,
)
from .construction_model import (
    compute_construction_job_years,
    compute_construction_job_years_from_intensity,
    spread_construction_job_years,
)
from .canada_inputs import (
    CanadaRegionalData,
    DEFAULT_CANADA_ELECTRICITY_PRICE_PATH,
    DEFAULT_CANADA_LOCAL_SHARE_PATH,
    DEFAULT_CANADA_MARGIN_PATH,
    DEFAULT_CANADA_PAYROLL_PATH,
    DEFAULT_CANADA_PROFILE_PATH,
)
from .io_loaders import load_datacenter_outputs
from .multipliers import (
    apply_multipliers,
    build_geo_multiplier_series,
    build_geo_constr_indirect_series,
    build_geo_constr_induced_series,
    build_geo_ops_indirect_series,
    build_geo_ops_induced_series,
    build_geo_constr_metric_per_direct_job_series,
    build_geo_ops_metric_per_direct_job_series,
)
from .operations_model import compute_operating_jobs
from .calibration import ECONOMIC_METHOD_VERSION, DataCenterCalibration
from .public_bea_lq_io import (
    DEFAULT_NORMALIZED_DIR,
    PublicBEALQIO,
    apply_public_bea_construction,
    apply_public_bea_operations,
)
from .spend_io import (
    DEFAULT_CONSTRUCTION_LOCALIZATION_PATH,
    DEFAULT_MARGIN_PATH,
    DEFAULT_SPEND_PROFILE_PATH,
    ConstructionLocalization,
    IOSystem,
    SpendProfile,
    apply_construction_spend_io,
    apply_operations_spend_io,
)
from employment.monetary import load_monetary_basis, normalize_aidc_money

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[3]


def _construction_method_arg(value: str) -> str:
    if value == "workers_per_mw":
        raise argparse.ArgumentTypeError(
            "'workers_per_mw' was removed: use 'lifecycle_intensity'; its coefficient "
            "already includes peak/average workforce, duration, and PUE conversion"
        )
    return value


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Estimate data-center campus construction + operations employment from a ReEDS-USCAN "
            "case's data-center IT capacity outputs using public regional I-O inputs; no Excel "
            "dependency."
        )
    )
    parser.add_argument(
        "--case-dir",
        type=Path,
        default=REPO_ROOT / "runs_save" / "v0626_G0-F0-S0",
        help="Path to a ReEDS case directory that contains outputs/datacenter_it_*.csv.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Directory for generated CSV outputs. Defaults to "
            "employment/datacenter_employment/results/<case-dir-name>/."
        ),
    )
    parser.add_argument(
        "--assumptions-file",
        type=Path,
        default=DEFAULT_ASSUMPTIONS_PATH,
        help="Path to the assumption register YAML.",
    )
    parser.add_argument(
        "--construction-method",
        type=_construction_method_arg,
        choices=["lifecycle_intensity", "capex"],
        default="lifecycle_intensity",
        help=(
            "lifecycle_intensity (default): MW-IT increment times the lifecycle construction "
            "job-years/MW-IT coefficient (see config/assumptions.yml). "
            "capex: sensitivity-only CAPEX fallback, requires --dollar-per-mw-construction."
        ),
    )
    parser.add_argument(
        "--dollar-per-mw-construction",
        type=float,
        default=None,
        help=(
            "USD per MW of new IT capacity, used only when --construction-method capex is "
            "selected, to convert datacenter_it_inv.csv MW increments to construction CAPEX. No "
            "default is shipped (see config/assumptions.yml) -- omitting this flag under "
            "--construction-method capex produces construction outputs flagged as missing "
            "(data_quality_flag=true) rather than a guessed number."
        ),
    )
    parser.add_argument(
        "--geo-multiplier-csv-us",
        type=Path,
        default=DEFAULT_US_GEO_MULT_PATH,
        help=(
            "Path to JEDI state-level multiplier CSV for US states. "
            "Generated by employment/energy_system/extract_io_multipliers.py. "
            f"Default: {DEFAULT_US_GEO_MULT_PATH}"
        ),
    )
    parser.add_argument(
        "--geo-multiplier-csv-can",
        type=Path,
        default=DEFAULT_CAN_GEO_MULT_PATH,
        help=(
            "Path to JEDI province-level multiplier CSV for Canada. "
            f"Default: {DEFAULT_CAN_GEO_MULT_PATH}"
        ),
    )
    parser.add_argument(
        "--indirect-method",
        choices=["public_bea_lq_io", "spend_io", "legacy_ratio"],
        default="public_bea_lq_io",
        help=(
            "public_bea_lq_io (default) is the public-data US academic method. "
            "spend_io and legacy_ratio are validation-only compatibility paths; invoke them via "
            "the validation_cli module for new validation runs."
        ),
    )
    parser.add_argument(
        "--public-bea-lq-dir",
        type=Path,
        default=DEFAULT_NORMALIZED_DIR,
        help=(
            "Normalized public BEA-LQ inputs produced by `python -m "
            f"employment.data_pipeline build`. Default: {DEFAULT_NORMALIZED_DIR}"
        ),
    )
    parser.add_argument(
        "--spend-profile-csv",
        type=Path,
        default=DEFAULT_SPEND_PROFILE_PATH,
        help=f"JEDI-style expenditure profile CSV. Default: {DEFAULT_SPEND_PROFILE_PATH}",
    )
    parser.add_argument(
        "--margin-csv",
        type=Path,
        default=DEFAULT_MARGIN_PATH,
        help=f"Purchaser-to-producer margin CSV. Default: {DEFAULT_MARGIN_PATH}",
    )
    parser.add_argument(
        "--construction-localization-csv",
        type=Path,
        default=DEFAULT_CONSTRUCTION_LOCALIZATION_PATH,
        help=(
            "Post-margin US construction retention rules. "
            f"Default: {DEFAULT_CONSTRUCTION_LOCALIZATION_PATH}"
        ),
    )
    parser.add_argument(
        "--canada-spend-profile",
        choices=["statcan_regional", "us_proxy_sensitivity"],
        default="statcan_regional",
        help=(
            "statcan_regional (default) uses province-specific Canadian CAPEX, supply-use, "
            "trade-flow, payroll and large-power inputs; us_proxy_sensitivity retains the "
            "former North American proxy for comparison only."
        ),
    )
    parser.add_argument(
        "--canada-regional-profile-csv",
        type=Path,
        default=DEFAULT_CANADA_PROFILE_PATH,
    )
    parser.add_argument(
        "--canada-local-share-csv",
        type=Path,
        default=DEFAULT_CANADA_LOCAL_SHARE_PATH,
    )
    parser.add_argument(
        "--canada-product-margin-csv",
        type=Path,
        default=DEFAULT_CANADA_MARGIN_PATH,
    )
    parser.add_argument(
        "--canada-electricity-price-csv",
        type=Path,
        default=DEFAULT_CANADA_ELECTRICITY_PRICE_PATH,
    )
    parser.add_argument(
        "--canada-payroll-csv",
        type=Path,
        default=DEFAULT_CANADA_PAYROLL_PATH,
    )
    parser.add_argument(
        "--construction-only",
        action="store_true",
        help="Only compute construction impacts.",
    )
    parser.add_argument(
        "--operations-only",
        action="store_true",
        help="Only compute operating impacts.",
    )
    parser.add_argument(
        "--min-output-impact-year",
        type=int,
        default=None,
        help="Optional minimum impact year to keep in annual outputs.",
    )
    return parser


def _resolve_output_dir(case_dir: Path, output_dir: Path | None) -> Path:
    if output_dir is not None:
        return output_dir
    return Path(__file__).resolve().parent / "results" / case_dir.name


def _mark_legacy_ratio(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    frame["impact_method"] = "legacy_ratio"
    frame["spend_profile_id"] = ""
    frame["spend_scale_method"] = "direct_job_ratio"
    frame["implied_total_spend_usd"] = float("nan")
    frame["local_final_demand_usd"] = float("nan")
    frame["io_implied_direct_jobs"] = float("nan")
    frame["direct_reconciliation_ratio"] = float("nan")
    frame["electricity_excluded_from_total"] = False
    frame["spend_profile_quality_flag"] = "legacy"
    return frame


def _mark_spend_io_metadata(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    frame["multiplier_scenario"] = "spend_io_14_industry"
    frame["job_multiplier_industry"] = "14_industry_spend_vector"
    frame["monetary_multiplier_industry"] = "14_industry_spend_vector"
    frame["job_multiplier_source"] = (
        "Extracted JEDI/StatCan 14-industry multipliers + spend_profiles.csv; "
        "see spend-impact detail"
    )
    return frame


def _mark_statcan_regional_metadata(frame: pd.DataFrame) -> pd.DataFrame:
    result = frame.copy()
    result["economic_method"] = "statcan_regional_io"
    result["economic_method_version"] = ECONOMIC_METHOD_VERSION
    result["impact_method"] = "statcan_regional_io"
    result["multiplier_scenario"] = "StatCan2022_regional"
    result["job_multiplier_industry"] = "StatCan provincial detailed industries"
    result["monetary_multiplier_industry"] = "StatCan provincial detailed industries"
    result["job_multiplier_source"] = (
        "Statistics Canada 36-10-0595-01 and 36-10-0478-01"
    )
    return result


def _mark_2022_intermediate(
    frame: pd.DataFrame, multiplier_context: str
) -> pd.DataFrame:
    result = normalize_aidc_money(
        frame,
        [],
        multiplier_context=multiplier_context,
        source_price_year=2022,
    )
    result["price_adjustment_factor"] = 1.0
    result["deflator_source"] = (
        "AIDC common 2022 USD intermediate; final 2022-to-2024 conversion pending"
    )
    result["currency"] = "USD"
    result["price_year"] = 2022
    return result


def _normalize_2024_usd(frame: pd.DataFrame) -> pd.DataFrame:
    if frame.empty:
        return frame
    if "price_year" in frame.columns:
        years = set(pd.to_numeric(frame["price_year"], errors="raise").astype(int))
        currencies = set(frame["currency"].dropna().astype(str))
        if years == {2024}:
            raise ValueError(
                "AIDC monetary values are already in 2024 USD; refusing double conversion"
            )
        if years != {2022} or currencies != {"USD"}:
            raise ValueError(
                f"AIDC final normalization requires a 2022 USD intermediate; "
                f"found currencies={currencies}, years={years}"
            )
    money_suffixes = (
        "_earnings_usd",
        "_output_usd",
        "_value_added_usd",
        "_compensation_usd",
        "_capex_usd",
        "_spend_usd",
        "_demand_usd",
        "_leakage_usd",
        "_crosscheck_usd",
        "_usd_per_mwh",
    )
    monetary_columns = [
        column for column in frame.columns if column.endswith(money_suffixes)
    ]
    if "electricity_spend_excluded_usd" in frame.columns:
        monetary_columns.append("electricity_spend_excluded_usd")
    result = normalize_aidc_money(
        frame,
        monetary_columns,
        source_price_year=2022,
    )
    return result.rename(
        columns={
            "electricity_price_2022_usd_per_mwh": "electricity_price_2024_usd_per_mwh"
        }
    )


def _normalize_output_2024_usd(frame: pd.DataFrame) -> pd.DataFrame:
    if frame.empty:
        return frame
    if "price_year" not in frame.columns:
        return _normalize_2024_usd(frame)
    years = pd.to_numeric(frame["price_year"], errors="raise").astype(int)
    unknown = set(years) - {2022, 2024}
    if unknown:
        raise ValueError(
            f"AIDC output contains unsupported price years: {sorted(unknown)}"
        )
    frames = []
    if years.eq(2022).any():
        frames.append(_normalize_2024_usd(frame.loc[years.eq(2022)].copy()))
    if years.eq(2024).any():
        native = frame.loc[years.eq(2024)].copy()
        if set(native["currency"].astype(str)) != {"USD"}:
            raise ValueError("Native 2024 AIDC rows must use USD")
        frames.append(native)
    return pd.concat(frames).sort_index()


def _write_campus_annual(
    construction: pd.DataFrame, operations: pd.DataFrame, output_dir: Path
) -> None:
    if construction.empty and operations.empty:
        columns = [
            "impact_year",
            "st",
            "country",
            "scenario",
            "construction_direct_job_years",
            "operating_direct_fte",
        ]
        for effect in ("direct", "indirect", "induced", "total"):
            columns.append(f"{effect}_jobs")
            columns.extend(
                f"{effect}_{metric}_usd"
                for metric in ("earnings", "output", "value_added")
            )
        columns.extend(
            [
                "currency",
                "price_year",
                "capacity_basis",
                "economic_method",
                "economic_method_version",
            ]
        )
        pd.DataFrame(columns=columns).to_csv(
            output_dir / "datacenter_campus_impacts_annual.csv", index=False
        )
        return
    keys = ["impact_year", "st", "country", "scenario"]
    pieces = []
    if not construction.empty:
        selected = construction[keys].copy()
        selected["construction_direct_job_years"] = construction[
            "direct_construction_job_years"
        ]
        selected["operating_direct_fte"] = 0.0
        for effect in ("direct", "indirect", "induced", "total"):
            selected[f"{effect}_jobs"] = construction[
                f"{effect}_construction_job_years"
            ]
            for metric in ("earnings", "output", "value_added"):
                selected[f"{effect}_{metric}_usd"] = construction[
                    f"{effect}_construction_{metric}_usd"
                ]
        pieces.append(selected)
    if not operations.empty:
        selected = operations[keys].copy()
        selected["construction_direct_job_years"] = 0.0
        selected["operating_direct_fte"] = operations["direct_operating_jobs"]
        for effect in ("direct", "indirect", "induced", "total"):
            selected[f"{effect}_jobs"] = operations[f"{effect}_operating_jobs"]
            for metric in ("earnings", "output", "value_added"):
                selected[f"{effect}_{metric}_usd"] = operations[
                    f"{effect}_operating_{metric}_usd"
                ]
        pieces.append(selected)
    values = [column for column in pieces[0].columns if column not in keys]
    campus = (
        pd.concat(pieces, ignore_index=True)
        .groupby(keys, as_index=False)[values]
        .sum(min_count=1)
        .sort_values(keys)
    )
    campus["currency"] = "USD"
    campus["price_year"] = 2024
    campus["capacity_basis"] = "IT"
    campus["economic_method"] = campus["country"].map(
        {"USA": "public_bea_lq_io", "CAN": "statcan_regional_io"}
    )
    campus["economic_method_version"] = ECONOMIC_METHOD_VERSION
    campus.to_csv(output_dir / "datacenter_campus_impacts_annual.csv", index=False)


def _run_construction(
    case_data,
    assumptions: AssumptionRegister,
    dollar_per_mw_construction: float | None,
    min_output_impact_year: int | None,
    geo_table: GeoMultiplierTable,
    construction_method: str = "lifecycle_intensity",
) -> pd.DataFrame:
    pue_conversion = assumptions.triplet("employment_pue_conversion").base
    if construction_method == "lifecycle_intensity":
        intensity_triplet = assumptions.triplet(
            "direct_construction_job_years_per_mw_it"
        )
        duration_triplet = assumptions.triplet("construction_duration_years")
    elif construction_method == "capex":
        beta_triplet = assumptions.triplet("beta_local")
        eta_triplet = assumptions.triplet("eta_constr")
        dollar_triplet = assumptions.triplet("dollar_per_mw_construction")
        duration_triplet = assumptions.triplet("construction_duration_years")
    else:
        raise ValueError(f"Unknown construction_method: {construction_method!r}")

    frames = []
    for scenario in SCENARIOS:
        if construction_method == "lifecycle_intensity":
            intensity = getattr(intensity_triplet, scenario)
            construction_duration_years = getattr(duration_triplet, scenario)
            per_increment = compute_construction_job_years_from_intensity(
                case_data.it_inv,
                case_data.modeled_years,
                intensity,
                construction_duration_years,
            )
        else:
            dollar_value = (
                dollar_per_mw_construction
                if dollar_per_mw_construction is not None
                else getattr(dollar_triplet, scenario)
            )
            beta_local = getattr(beta_triplet, scenario)
            eta_constr = getattr(eta_triplet, scenario)
            construction_duration_years = getattr(duration_triplet, scenario)
            per_increment = compute_construction_job_years(
                case_data.it_inv,
                case_data.modeled_years,
                dollar_value,
                beta_local,
                eta_constr,
                construction_duration_years,
            )

        annual = spread_construction_job_years(per_increment, min_output_impact_year)
        if annual.empty:
            continue
        annual["construction_mw_weighted"] = (
            annual["deployment_mw"] * annual["construction_allocation_fraction"]
        )

        direct = annual["direct_construction_job_years"]
        m_indirect = build_geo_constr_indirect_series(annual["st"], geo_table, scenario)
        m_induced = build_geo_constr_induced_series(annual["st"], geo_table, scenario)
        annual["indirect_construction_job_years"] = direct * m_indirect
        annual["induced_construction_job_years"] = direct * m_induced
        m_total = build_geo_multiplier_series(
            annual["st"], geo_table, "construction", scenario
        )
        _, total = apply_multipliers(direct, m_total)
        annual["total_construction_job_years"] = total


        missing_multiplier = pd.Series(False, index=annual.index)
        for metric in ("earnings", "output", "value_added"):
            for effect in ("direct", "indirect", "induced"):
                ratio = build_geo_constr_metric_per_direct_job_series(
                    annual["st"], geo_table, metric, effect, scenario
                )
                missing_multiplier = missing_multiplier | ratio.isna()
                annual[f"{effect}_construction_{metric}_usd"] = direct * ratio
            annual[f"total_construction_{metric}_usd"] = (
                annual[f"direct_construction_{metric}_usd"]
                + annual[f"indirect_construction_{metric}_usd"]
                + annual[f"induced_construction_{metric}_usd"]
            )



        annual["earnings_output_data_quality_flag"] = missing_multiplier

        annual["scenario"] = scenario
        annual["multiplier_scenario"] = geo_table.name
        annual["job_multiplier_industry"] = annual["st"].map(
            lambda region: geo_table.job_multiplier_industry(region, "construction")
        )
        annual["job_multiplier_source"] = annual["st"].map(
            lambda region: geo_table.job_multiplier_source(region, "construction")
        )
        annual["job_multiplier_data_year"] = annual["st"].map(
            lambda region: geo_table.job_multiplier_data_year(region, "construction")
        )
        annual["monetary_multiplier_industry"] = annual["st"].map(
            lambda region: geo_table.monetary_multiplier_industry(
                region, "construction"
            )
        )
        annual["construction_method"] = construction_method
        annual["capacity_basis"] = "IT"
        annual["pue_conversion"] = pue_conversion
        annual["province_wage_index_to_canada"] = annual["st"].map(
            geo_table.provincial_wage_index
        )
        annual["province_wage_data_source"] = annual["st"].map(
            geo_table.provincial_wage_source
        )
        frames.append(annual)

    if not frames:
        return pd.DataFrame()
    result = pd.concat(frames, ignore_index=True)
    result = result.merge(case_data.hierarchy, on="st", how="left")
    result = _mark_2022_intermediate(result, "construction")
    value_columns = [
        "construction_mw_weighted",
        "direct_construction_job_years",
        "indirect_construction_job_years",
        "induced_construction_job_years",
        "total_construction_job_years",
        *[
            f"{effect}_construction_{metric}_usd"
            for metric in ("earnings", "output", "value_added")
            for effect in ("direct", "indirect", "induced", "total")
        ],
    ]
    id_columns = [
        "impact_year",
        "st",
        "country",
        "scenario",
        "multiplier_scenario",
        "job_multiplier_industry",
        "job_multiplier_source",
        "job_multiplier_data_year",
        "monetary_multiplier_industry",
        "construction_method",
        "direct_construction_job_years_per_mw_it",
        "construction_duration_years",
        "capacity_basis",
        "pue_conversion",
        "dollar_per_mw_construction",
        "beta_local",
        "eta_constr",
        "data_quality_flag",
        "earnings_output_data_quality_flag",
        "province_wage_index_to_canada",
        "province_wage_data_source",
        "source_currency",
        "multiplier_source_currency",
        "source_price_year",
        "fx_source_currency_per_usd",
        "price_adjustment_factor",
        "multiplier_data_year",
        "multiplier_data_vintages",
        "deflator_source",
        "fx_application",
        "monetary_basis_verified",
        "currency",
        "price_year",
    ]
    result = result.groupby(id_columns, as_index=False, dropna=False)[
        value_columns
    ].sum(min_count=1)
    columns = [
        "impact_year",
        "st",
        "country",
        "scenario",
        "multiplier_scenario",
        "job_multiplier_industry",
        "job_multiplier_source",
        "job_multiplier_data_year",
        "monetary_multiplier_industry",
        "construction_method",
        "direct_construction_job_years_per_mw_it",
        "construction_duration_years",
        "capacity_basis",
        "pue_conversion",
        "dollar_per_mw_construction",
        "beta_local",
        "eta_constr",
        "construction_mw_weighted",
        "data_quality_flag",
        "earnings_output_data_quality_flag",
        "province_wage_index_to_canada",
        "province_wage_data_source",
        "direct_construction_job_years",
        "indirect_construction_job_years",
        "induced_construction_job_years",
        "total_construction_job_years",
        "direct_construction_earnings_usd",
        "indirect_construction_earnings_usd",
        "induced_construction_earnings_usd",
        "total_construction_earnings_usd",
        "direct_construction_output_usd",
        "indirect_construction_output_usd",
        "induced_construction_output_usd",
        "total_construction_output_usd",
        "direct_construction_value_added_usd",
        "indirect_construction_value_added_usd",
        "induced_construction_value_added_usd",
        "total_construction_value_added_usd",
        "source_currency",
        "multiplier_source_currency",
        "source_price_year",
        "fx_source_currency_per_usd",
        "price_adjustment_factor",
        "multiplier_data_year",
        "multiplier_data_vintages",
        "deflator_source",
        "fx_application",
        "monetary_basis_verified",
        "currency",
        "price_year",
    ]
    return (
        result[columns]
        .sort_values(["impact_year", "st", "scenario"])
        .reset_index(drop=True)
    )


def _run_operations(
    case_data,
    assumptions: AssumptionRegister,
    min_output_impact_year: int | None,
    geo_table: GeoMultiplierTable,
) -> pd.DataFrame:
    jobs_per_mw_triplet = assumptions.triplet("direct_jobs_per_mw_operating")
    pue_conversion = assumptions.triplet("employment_pue_conversion").base

    frames = []
    for scenario in SCENARIOS:
        jobs_per_mw = getattr(jobs_per_mw_triplet, scenario)
        if jobs_per_mw is None:
            logger.warning(
                "direct_jobs_per_mw_operating.%s is null; skipping operations scenario %r.",
                scenario,
                scenario,
            )
            continue
        annual = compute_operating_jobs(
            case_data.it_cap,
            case_data.modeled_years,
            jobs_per_mw,
            min_output_impact_year,
        )
        annual["capacity_basis"] = "IT"
        annual["pue_conversion"] = pue_conversion

        direct = annual["direct_operating_jobs"]
        m_indirect = build_geo_ops_indirect_series(annual["st"], geo_table, scenario)
        m_induced = build_geo_ops_induced_series(annual["st"], geo_table, scenario)
        annual["indirect_operating_jobs"] = direct * m_indirect
        annual["induced_operating_jobs"] = direct * m_induced
        m_total = build_geo_multiplier_series(
            annual["st"], geo_table, "operations", scenario
        )
        _, total = apply_multipliers(direct, m_total)
        annual["total_operating_jobs"] = total


        missing_multiplier = pd.Series(False, index=annual.index)
        for metric in ("earnings", "output", "value_added"):
            for effect in ("direct", "indirect", "induced"):
                ratio = build_geo_ops_metric_per_direct_job_series(
                    annual["st"], geo_table, metric, effect, scenario
                )
                missing_multiplier = missing_multiplier | ratio.isna()
                annual[f"{effect}_operating_{metric}_usd"] = direct * ratio
            annual[f"total_operating_{metric}_usd"] = (
                annual[f"direct_operating_{metric}_usd"]
                + annual[f"indirect_operating_{metric}_usd"]
                + annual[f"induced_operating_{metric}_usd"]
            )



        annual["earnings_output_data_quality_flag"] = missing_multiplier

        annual["scenario"] = scenario
        annual["multiplier_scenario"] = geo_table.name
        annual["job_multiplier_industry"] = annual["st"].map(
            lambda region: geo_table.job_multiplier_industry(region, "operations")
        )
        annual["job_multiplier_source"] = annual["st"].map(
            lambda region: geo_table.job_multiplier_source(region, "operations")
        )
        annual["job_multiplier_data_year"] = annual["st"].map(
            lambda region: geo_table.job_multiplier_data_year(region, "operations")
        )
        annual["monetary_multiplier_industry"] = annual["st"].map(
            lambda region: geo_table.monetary_multiplier_industry(region, "operations")
        )
        annual["province_wage_index_to_canada"] = annual["st"].map(
            geo_table.provincial_wage_index
        )
        annual["province_wage_data_source"] = annual["st"].map(
            geo_table.provincial_wage_source
        )
        frames.append(annual)

    if not frames:
        return pd.DataFrame()
    result = pd.concat(frames, ignore_index=True)
    result = result.merge(case_data.hierarchy, on="st", how="left")
    result = _mark_2022_intermediate(result, "operations")
    columns = [
        "impact_year",
        "st",
        "country",
        "scenario",
        "multiplier_scenario",
        "job_multiplier_industry",
        "job_multiplier_source",
        "job_multiplier_data_year",
        "monetary_multiplier_industry",
        "mw_stock",
        "direct_jobs_per_mw_operating",
        "capacity_basis",
        "pue_conversion",
        "direct_operating_jobs",
        "indirect_operating_jobs",
        "induced_operating_jobs",
        "total_operating_jobs",
        "earnings_output_data_quality_flag",
        "province_wage_index_to_canada",
        "province_wage_data_source",
        "direct_operating_earnings_usd",
        "indirect_operating_earnings_usd",
        "induced_operating_earnings_usd",
        "total_operating_earnings_usd",
        "direct_operating_output_usd",
        "indirect_operating_output_usd",
        "induced_operating_output_usd",
        "total_operating_output_usd",
        "direct_operating_value_added_usd",
        "indirect_operating_value_added_usd",
        "induced_operating_value_added_usd",
        "total_operating_value_added_usd",
        "is_interpolated",
        "source_currency",
        "multiplier_source_currency",
        "source_price_year",
        "fx_source_currency_per_usd",
        "price_adjustment_factor",
        "multiplier_data_year",
        "multiplier_data_vintages",
        "deflator_source",
        "fx_application",
        "monetary_basis_verified",
        "currency",
        "price_year",
    ]
    return (
        result[columns]
        .sort_values(["impact_year", "st", "scenario"])
        .reset_index(drop=True)
    )


def _write_summary(
    annual: pd.DataFrame, value_cols: list[str], output_path: Path
) -> None:
    if annual.empty:
        return
    summary = (
        annual.groupby(
            ["impact_year", "scenario", "multiplier_scenario"], as_index=False
        )[value_cols]
        .sum()
        .sort_values(["impact_year", "scenario"])
    )
    summary["currency"] = "USD"
    summary["price_year"] = int(load_monetary_basis()["target_price_year"])
    summary.to_csv(output_path, index=False)


def _write_context(case_data, output_dir: Path) -> None:
    frames = []
    if case_data.load_st is not None:
        frames.append(case_data.load_st.rename(columns={"Value": "dc_load_mw"}))
    if case_data.load_st_base is not None:
        base = case_data.load_st_base.rename(columns={"Value": "dc_load_mw_base"})
        if frames:
            frames[0] = frames[0].merge(base, on=["st", "t"], how="outer")
        else:
            frames.append(base)
    if frames:
        frames[0].rename(columns={"t": "impact_year"}).to_csv(
            output_dir / "datacenter_context.csv", index=False
        )


_PUBLIC_AUDIT_JOBS = {
    "construction": {
        "VA": {
            "direct": 35_110.0,
            "indirect": 9_945.0,
            "induced": 13_992.0,
            "total": 59_047.0,
            "direct_definition": "construction_plus_equipment_direct",
            "source": "Virginia JLARC report 598 Table D-3",
        },
        "MN": {
            "direct": 2_292.0,
            "indirect": 507.0,
            "induced": 776.0,
            "total": 3_575.0,
            "direct_definition": "construction_industry_direct",
            "source": "Minnesota LBO data-center exemption evaluation Table 3",
        },
        "GA": {
            "direct": 15_809.0,
            "indirect": 4_954.0,
            "induced": 7_587.0,
            "total": 28_350.0,
            "direct_definition": "construction_industry_direct",
            "source": "Georgia DOAA data-center exemption evaluation Table 3",
        },
    },
    "operations": {
        "VA": {
            "direct": 4_373.0,
            "indirect": 6_615.0,
            "induced": 3_830.0,
            "total": 14_817.0,
            "direct_definition": "datacenter_employee_direct",
            "source": "Virginia JLARC report 598 Table D-5",
        },
        "MN": {
            "direct": 677.0,
            "indirect": 315.0,
            "induced": 385.0,
            "total": 1_377.0,
            "direct_definition": "datacenter_employee_direct",
            "source": "Minnesota LBO data-center exemption evaluation Table 4",
        },
        "GA": {
            "direct": 1_873.0,
            "indirect": 1_815.0,
            "induced": 1_783.0,
            "total": 5_471.0,
            "direct_definition": "datacenter_employee_direct",
            "source": "Georgia DOAA data-center exemption evaluation Table 4",
        },
    },
}


def _add_construction_benchmark_warnings(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    frame["construction_benchmark_warning"] = pd.Series(
        pd.NA, index=frame.index, dtype="boolean"
    )
    if frame.empty:
        return frame
    direct_col = "audit_modeled_direct_construction_job_years"
    total_col = "audit_modeled_total_construction_job_years"
    if direct_col not in frame or total_col not in frame:
        direct_col = "direct_construction_job_years"
        total_col = "total_construction_job_years"
    for (region, scenario), group in frame.groupby(["st", "scenario"]):
        audit = _PUBLIC_AUDIT_JOBS["construction"].get(str(region))
        if audit is None:
            continue
        direct = float(group[direct_col].sum())
        total = float(group[total_col].sum())
        if direct <= 0:
            continue
        modeled_ratio = total / direct
        audit_ratio = audit["total"] / audit["direct"]
        warning = abs(modeled_ratio / audit_ratio - 1.0) > 0.25
        frame.loc[group.index, "construction_benchmark_warning"] = warning
    return frame


def _write_public_audit_benchmarks(
    construction: pd.DataFrame,
    operations: pd.DataFrame,
    output_dir: Path,
) -> None:
    rows = []
    phase_frames = {
        "construction": (
            construction,
            "audit_modeled_direct_construction_job_years",
            "audit_modeled_indirect_construction_job_years",
            "audit_modeled_induced_construction_job_years",
            "audit_modeled_total_construction_job_years",
        ),
        "operations": (
            operations,
            "direct_operating_jobs",
            "indirect_operating_jobs",
            "induced_operating_jobs",
            "total_operating_jobs",
        ),
    }
    for phase, (
        frame,
        direct_col,
        indirect_col,
        induced_col,
        total_col,
    ) in phase_frames.items():
        if frame.empty:
            continue
        if direct_col not in frame:
            if phase == "construction":
                direct_col = "direct_construction_job_years"
                indirect_col = "indirect_construction_job_years"
                induced_col = "induced_construction_job_years"
                total_col = "total_construction_job_years"
            else:
                direct_col = "direct_operating_jobs"
        for region, audit in _PUBLIC_AUDIT_JOBS[phase].items():
            selected = (
                frame[frame["st"].eq(region)] if not frame.empty else pd.DataFrame()
            )
            for scenario in SCENARIOS:
                scenario_rows = selected[selected["scenario"].eq(scenario)]
                direct = (
                    float(scenario_rows[direct_col].sum())
                    if not scenario_rows.empty
                    else 0.0
                )
                indirect = (
                    float(scenario_rows[indirect_col].sum())
                    if not scenario_rows.empty
                    else 0.0
                )
                induced = (
                    float(scenario_rows[induced_col].sum())
                    if not scenario_rows.empty
                    else 0.0
                )
                total = (
                    float(scenario_rows[total_col].sum())
                    if not scenario_rows.empty
                    else 0.0
                )
                observed_ratio = total / direct if direct > 0 else float("nan")
                audit_ratio = audit["total"] / audit["direct"]
                relative_error = (
                    observed_ratio / audit_ratio - 1.0
                    if pd.notna(observed_ratio)
                    else float("nan")
                )
                comparison_available = direct > 0
                reconciliation = (
                    float(scenario_rows["direct_reconciliation_ratio"].mean())
                    if "direct_reconciliation_ratio" in scenario_rows
                    and not scenario_rows.empty
                    else float("nan")
                )
                ratio_ok = bool(
                    pd.notna(relative_error) and abs(relative_error) <= 0.25
                )
                reconciliation_ok = bool(
                    pd.isna(reconciliation) or 0.75 <= reconciliation <= 1.25
                )
                rows.append(
                    {
                        "phase": phase,
                        "region": region,
                        "scenario": scenario,
                        "modeled_direct": direct,
                        "modeled_indirect": indirect,
                        "modeled_induced": induced,
                        "modeled_total": total,
                        "modeled_total_to_direct": observed_ratio,
                        "audit_direct": audit["direct"],
                        "audit_indirect": audit["indirect"],
                        "audit_induced": audit["induced"],
                        "audit_total": audit["total"],
                        "audit_total_to_direct": audit_ratio,
                        "relative_error": relative_error,
                        "within_25pct": ratio_ok,
                        "scope_comparable": comparison_available,
                        "modeled_direct_definition": (
                            audit["direct_definition"]
                            if phase == "construction"
                            else "datacenter_employee_direct"
                        ),
                        "benchmark_direct_definition": audit["direct_definition"],
                        "result_rule_scope": (
                            "audit_only_same_scope"
                            if phase == "construction"
                            else "main_result"
                        ),
                        "main_result_rule_id": (
                            str(scenario_rows["construction_spend_rule_id"].iloc[0])
                            if phase == "construction"
                            and not scenario_rows.empty
                            and "construction_spend_rule_id" in scenario_rows
                            else "not_applicable"
                        ),
                        "audit_rule_id": (
                            str(scenario_rows["construction_audit_rule_id"].iloc[0])
                            if phase == "construction"
                            and not scenario_rows.empty
                            and "construction_audit_rule_id" in scenario_rows
                            else "not_applicable"
                        ),
                        "observed_total_to_direct": observed_ratio,
                        "audit_region_total_to_direct": audit_ratio,
                        "audit_range_lower": audit_ratio * 0.75,
                        "audit_range_upper": audit_ratio * 1.25,
                        "direct_reconciliation_ratio": reconciliation,
                        "comparison_available": comparison_available,
                        "total_to_direct_in_audit_range": ratio_ok,
                        "reconciliation_in_0_75_to_1_25": reconciliation_ok,
                        "quality_warning": comparison_available
                        and not (ratio_ok and reconciliation_ok),
                        "audit_source": audit["source"],
                        "notes": (
                            "Construction uses an audit-only same-scope vector for comparison; "
                            "the published main result remains on the uniform Minnesota-style "
                            "conservative rule. No multiplier or main result is adjusted."
                            if phase == "construction"
                            else "Exact-state, definition-aware comparison; no multiplier or "
                            "result is silently adjusted."
                        ),
                    }
                )
    report = pd.DataFrame(rows)
    report.to_csv(output_dir / "datacenter_public_audit_benchmarks.csv", index=False)
    if not report.empty:
        warnings = int(report["quality_warning"].sum())
        if warnings:
            logger.warning(
                "%d public-audit benchmark rows are outside the stated range; see %s.",
                warnings,
                output_dir / "datacenter_public_audit_benchmarks.csv",
            )


def _write_assumptions_used(
    assumptions: AssumptionRegister,
    dollar_per_mw_construction: float | None,
    output_dir: Path,
    construction_method: str = "lifecycle_intensity",
    indirect_method: str = "public_bea_lq_io",
) -> None:
    rows = []
    for name in (
        "direct_construction_job_years_per_mw_it",
        "peak_construction_workers_per_mw_facility",
        "average_to_peak_construction_workforce_ratio",
        "employment_pue_conversion",
        "construction_duration_years",
        "direct_jobs_per_mw_operating",
        "dc_capex_share_land",
        "dc_capex_share_construction",
        "dc_capex_share_equipment",
        "dc_capex_share_other",
        "dc_equipment_to_construction_ratio",
        "dc_equipment_indirect_local_share",
        "dc_operating_employee_comp_share",
        "dc_operating_electricity_share",
        "dc_operating_value_added_share",
    ):
        t = assumptions.triplet(name)
        rows.append(
            {
                "parameter": name,
                "low": t.low,
                "base": t.base,
                "high": t.high,
                "citation": t.citation,
            }
        )
    rows.append(
        {
            "parameter": "indirect_method",
            "low": indirect_method,
            "base": indirect_method,
            "high": indirect_method,
            "citation": "--indirect-method public_bea_lq_io; validation: spend_io|legacy_ratio",
        }
    )
    if construction_method != "lifecycle_intensity":
        for name in ("beta_local", "eta_constr", "dollar_per_mw_construction"):
            t = assumptions.triplet(name)
            rows.append(
                {
                    "parameter": name,
                    "low": t.low,
                    "base": t.base,
                    "high": t.high,
                    "citation": t.citation,
                }
            )
    if indirect_method != "public_bea_lq_io":
        t = assumptions.triplet("direct_payroll_spendable_share")
        rows.append(
            {
                "parameter": "direct_payroll_spendable_share",
                "low": t.low,
                "base": t.base,
                "high": t.high,
                "citation": t.citation,
            }
        )
    rows.append(
        {
            "parameter": "economic_method_version",
            "low": ECONOMIC_METHOD_VERSION,
            "base": ECONOMIC_METHOD_VERSION,
            "high": ECONOMIC_METHOD_VERSION,
            "citation": "production method schema identifier",
        }
    )
    rows.append(
        {
            "parameter": "construction_method",
            "low": construction_method,
            "base": construction_method,
            "high": construction_method,
            "citation": "supplied via --construction-method",
        }
    )
    monetary_basis = load_monetary_basis()
    rows.append(
        {
            "parameter": "analysis_currency",
            "low": monetary_basis["target_currency"],
            "base": monetary_basis["target_currency"],
            "high": monetary_basis["target_currency"],
            "citation": "employment/monetary_basis.yml",
        }
    )
    rows.append(
        {
            "parameter": "analysis_price_year",
            "low": monetary_basis["target_price_year"],
            "base": monetary_basis["target_price_year"],
            "high": monetary_basis["target_price_year"],
            "citation": "employment/monetary_basis.yml; inputs/financials/deflator.csv",
        }
    )
    pd.DataFrame(rows).to_csv(output_dir / "assumptions_used.csv", index=False)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    parser = build_arg_parser()
    args = parser.parse_args()

    output_dir = _resolve_output_dir(args.case_dir, args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    assumptions = AssumptionRegister.load(args.assumptions_file)
    calibration = DataCenterCalibration.from_assumptions(assumptions)
    case_data = load_datacenter_outputs(args.case_dir)

    geo_table = GeoMultiplierTable.load(
        us_path=args.geo_multiplier_csv_us,
        can_path=args.geo_multiplier_csv_can,
    )
    logger.info(
        "Loaded JEDI state-level geo multiplier table (%d region×industry rows).",
        len(geo_table._data),
    )

    io_system = None
    public_us_model = None
    spend_profiles = None
    construction_localization = None
    canada_data = None
    if args.indirect_method in {"public_bea_lq_io", "spend_io"}:
        io_system = IOSystem.load(
            us_path=args.geo_multiplier_csv_us,
            can_path=args.geo_multiplier_csv_can,
            margin_path=args.margin_csv,
            include_canada_proxy_margins=(
                args.canada_spend_profile == "us_proxy_sensitivity"
            ),
        )
        spend_profiles = SpendProfile.load(args.spend_profile_csv)
        if args.indirect_method == "spend_io":
            construction_localization = ConstructionLocalization.load(
                args.construction_localization_csv
            )
        else:
            public_us_model = PublicBEALQIO.load(
                args.public_bea_lq_dir, calibration=calibration
            )
        if args.canada_spend_profile == "statcan_regional":
            canada_data = CanadaRegionalData.load(
                profile_path=args.canada_regional_profile_csv,
                local_share_path=args.canada_local_share_csv,
                margin_path=args.canada_product_margin_csv,
                electricity_price_path=args.canada_electricity_price_csv,
                payroll_path=args.canada_payroll_csv,
            )
        if args.indirect_method == "public_bea_lq_io":
            logger.info(
                "Loaded public BEA-LQ US system (%d detailed industries) and StatCan Canada system.",
                len(public_us_model.industries),
            )
        else:
            logger.info(
                "Loaded validation-only 14-industry I-O system (%d multiplier rows).",
                len(io_system.data),
            )

    construction = pd.DataFrame()
    operations = pd.DataFrame()
    if not args.operations_only:
        construction = _run_construction(
            case_data,
            assumptions,
            args.dollar_per_mw_construction,
            args.min_output_impact_year,
            geo_table,
            args.construction_method,
        )
        if args.indirect_method == "public_bea_lq_io" and not construction.empty:
            result_frames = []
            detail_frames = []
            us_rows = construction[construction["country"].eq("USA")]
            can_rows = construction[construction["country"].eq("CAN")]
            if not us_rows.empty:
                result, detail = apply_public_bea_construction(us_rows, public_us_model)
                result_frames.append(result)
                detail_frames.append(detail)
            if not can_rows.empty:
                result, detail = apply_construction_spend_io(
                    can_rows,
                    io_system,
                    spend_profiles,
                    canada_data=canada_data,
                    canada_spend_profile="statcan_regional",
                    calibration=calibration,
                )
                result_frames.append(_mark_statcan_regional_metadata(result))
                detail_frames.append(
                    _mark_statcan_regional_metadata(
                        _mark_2022_intermediate(detail, "construction")
                    )
                )
            construction = pd.concat(result_frames, ignore_index=True)
            construction_detail = _normalize_output_2024_usd(
                pd.concat(detail_frames, ignore_index=True)
            )
            construction_detail.to_csv(
                output_dir / "datacenter_construction_spend_impacts_annual.csv",
                index=False,
            )
        elif args.indirect_method == "spend_io" and not construction.empty:
            construction, construction_detail = apply_construction_spend_io(
                construction,
                io_system,
                spend_profiles,
                canada_data=canada_data,
                canada_spend_profile=args.canada_spend_profile,
                construction_localization=construction_localization,
                calibration=calibration,
            )
            construction = _mark_spend_io_metadata(construction)
            construction_detail = _normalize_output_2024_usd(construction_detail)
            construction_detail.to_csv(
                output_dir / "datacenter_construction_spend_impacts_annual.csv",
                index=False,
            )
        elif not construction.empty:
            construction = _mark_legacy_ratio(construction)
            construction["construction_spend_rule_id"] = "legacy_ratio"
            construction["construction_audit_rule_id"] = "not_applicable"
            construction["construction_spend_scope"] = "not_applicable"
            construction["construction_io_calibration_status"] = "not_applicable"
            construction["equipment_direct_construction_job_years"] = 0.0
            construction["audit_comparable_direct_construction_job_years"] = (
                construction["direct_construction_job_years"]
            )
            for effect in ("direct", "indirect", "induced", "total"):
                construction[f"audit_modeled_{effect}_construction_job_years"] = (
                    construction[f"{effect}_construction_job_years"]
                )
        construction = _normalize_output_2024_usd(construction)
        if args.indirect_method == "public_bea_lq_io" and not construction.empty:
            construction["economic_method_version"] = ECONOMIC_METHOD_VERSION
        if args.indirect_method == "spend_io":
            construction = _add_construction_benchmark_warnings(construction)
        construction.to_csv(
            output_dir / "datacenter_construction_impacts_annual.csv", index=False
        )
        _write_summary(
            construction,
            [
                "direct_construction_job_years",
                "indirect_construction_job_years",
                "induced_construction_job_years",
                "total_construction_job_years",
                "direct_construction_earnings_usd",
                "indirect_construction_earnings_usd",
                "induced_construction_earnings_usd",
                "total_construction_earnings_usd",
                "direct_construction_output_usd",
                "indirect_construction_output_usd",
                "induced_construction_output_usd",
                "total_construction_output_usd",
                "direct_construction_value_added_usd",
                "indirect_construction_value_added_usd",
                "induced_construction_value_added_usd",
                "total_construction_value_added_usd",
            ],
            output_dir / "datacenter_construction_impacts_annual_summary.csv",
        )

    if not args.construction_only:
        operations = _run_operations(
            case_data,
            assumptions,
            args.min_output_impact_year,
            geo_table,
        )
        if (
            args.indirect_method in {"public_bea_lq_io", "spend_io"}
            and not operations.empty
        ):
            payroll_share = assumptions.triplet("direct_payroll_spendable_share")
            operations_frames = []
            vendor_frames = []
            electricity_frames = []
            for scenario in SCENARIOS:
                selected = operations[operations["scenario"].eq(scenario)].copy()
                if selected.empty:
                    continue
                if args.indirect_method == "public_bea_lq_io":
                    us_rows = selected[selected["country"].eq("USA")]
                    can_rows = selected[selected["country"].eq("CAN")]
                    if not us_rows.empty:
                        adjusted, vendor, electricity = apply_public_bea_operations(
                            us_rows, public_us_model
                        )
                        operations_frames.append(adjusted)
                        vendor_frames.append(vendor)
                        electricity_frames.append(electricity)
                    if not can_rows.empty:
                        adjusted, vendor, electricity = apply_operations_spend_io(
                            can_rows,
                            io_system,
                            spend_profiles,
                            getattr(payroll_share, scenario),
                            case_data.load_st,
                            canada_data=canada_data,
                            canada_spend_profile="statcan_regional",
                            calibration=calibration,
                        )
                        operations_frames.append(
                            _mark_statcan_regional_metadata(adjusted)
                        )
                        vendor_frames.append(
                            _mark_statcan_regional_metadata(
                                _mark_2022_intermediate(vendor, "operations")
                            )
                        )
                        electricity_frames.append(
                            _mark_statcan_regional_metadata(
                                _mark_2022_intermediate(electricity, "operations")
                            )
                        )
                else:
                    adjusted, vendor, electricity = apply_operations_spend_io(
                        selected,
                        io_system,
                        spend_profiles,
                        getattr(payroll_share, scenario),
                        case_data.load_st,
                        canada_data=canada_data,
                        canada_spend_profile=args.canada_spend_profile,
                        calibration=calibration,
                    )
                    operations_frames.append(adjusted)
                    vendor_frames.append(vendor)
                    electricity_frames.append(electricity)
            operations = pd.concat(operations_frames, ignore_index=True)
            vendor_detail = _normalize_output_2024_usd(
                pd.concat(vendor_frames, ignore_index=True)
            )
            electricity_detail = _normalize_output_2024_usd(
                pd.concat(electricity_frames, ignore_index=True)
            )
            operations = _normalize_output_2024_usd(operations)
            if args.indirect_method == "public_bea_lq_io" and not operations.empty:
                operations["economic_method_version"] = ECONOMIC_METHOD_VERSION
            if args.indirect_method == "spend_io":
                operations = _mark_spend_io_metadata(operations)
            vendor_detail.to_csv(
                output_dir / "datacenter_operating_spend_impacts_annual.csv",
                index=False,
            )
            electricity_detail.to_csv(
                output_dir / "datacenter_electricity_impacts_annual.csv",
                index=False,
            )
        else:
            operations = _mark_legacy_ratio(operations)
            operations = _normalize_output_2024_usd(operations)
        operations.to_csv(
            output_dir / "datacenter_operating_impacts_annual.csv", index=False
        )
        _write_summary(
            operations,
            [
                "direct_operating_jobs",
                "indirect_operating_jobs",
                "induced_operating_jobs",
                "total_operating_jobs",
                "direct_operating_earnings_usd",
                "indirect_operating_earnings_usd",
                "induced_operating_earnings_usd",
                "total_operating_earnings_usd",
                "direct_operating_output_usd",
                "indirect_operating_output_usd",
                "induced_operating_output_usd",
                "total_operating_output_usd",
                "direct_operating_value_added_usd",
                "indirect_operating_value_added_usd",
                "induced_operating_value_added_usd",
                "total_operating_value_added_usd",
            ],
            output_dir / "datacenter_operating_impacts_annual_summary.csv",
        )

    _write_campus_annual(construction, operations, output_dir)
    if args.indirect_method == "spend_io":
        _write_public_audit_benchmarks(construction, operations, output_dir)
    else:

        audit_path = output_dir / "datacenter_public_audit_benchmarks.csv"
        if audit_path.exists():
            audit_path.unlink()

    _write_context(case_data, output_dir)
    _write_assumptions_used(
        assumptions,
        args.dollar_per_mw_construction,
        output_dir,
        args.construction_method,
        args.indirect_method,
    )
    logger.info("Wrote outputs to %s", output_dir)


if __name__ == "__main__":
    main()
